### ISSUE TITLE
About Performace on Terrestrial Dataset?

### ISSUE THREAD

**Issue by 050644zf** [LiPang/HSIGene#4]
I just read your excellent work on HSI generation, which inspired me a lot.

However, I found only arieal datasets are being used in this work. And I wonder, will the performace of HSIGene be degraded when using terrestrial datasets like [ICVL](https://icvl.cs.bgu.ac.il/hyperspectral/), [CAVE](https://www.cs.columbia.edu/CAVE/databases/multispectral/), [ARAD_1K](https://github.com/boazarad/ARAD_1K). Cuz the terrestrial dataset are obviouly more spatially complicated than arieal one.

So since I don't have the resources to train one, I wanna know if you have tested HSIGene on terrestrial datasets and what the performace looks like. 

Regrads.

**Comment by LiPang** [comment]
As you've pointed out, generating HSIs of ground objects is more challenging compared to remote sensing images. This is because the semantic information in remote sensing images remains unchanged under rotation, flipping, and local magnification, which is not true for ground objects. This limitation restricts the application of image augmentation techniques on ground object images, thereby limiting the number of training images.  However, given the greater diversity in textures and details of ground objects, generating new data requires a larger amount of data. We will consider this as a future research direction. Thanks for your suggestion..

**Comment by 050644zf** [comment]
Thanks for your detailed explaination! Now I have better understanding on the difficulty of ground image generation.
